#jupyter nbconvert --execute --to html test-run-with-command-line.ipynb
#jupyter nbconvert --to ipynb --execute ./test-run-with-command-line.ipynb --output "1403-08-27.ipynb"
log:
    level: INFO
    format: "%(asctime)s | %(levelname)s | %(message)s"
    mode: both
    colored_console: True
    # Note: The name and path of the log file are set in the settings section for each code.
    filepath: "{dataset.path.dataset}" # Set in the subset config.
    filename_prefix: mk_dataset
    filename: "{project.name}_{timestamp}" # if set to "now", the current date set as the logfile name.
    filename_timestamp: null

dataset:
    data_format:
        dimension_order: CW
        component_order: ZNE
        sampling_rate: 100
        measurement: velocity
        unit: counts
        instrument_response: not restituted
    preprocess:
        merge_method: 1
        fill_value: 0
    trim:
        before: 5
        after: 25
    save_streams:
        enabled: False
        format: MSEED
    path:
        catalog: D:\Catalogs\{project.name}.out
        inventory: D:\Inventory\DataLess\*\*\*.dlsv
        stream_root: D:\Local_Network_Data-SeisComP\{project.name}
        stream_pattern: '{time.year}/{project.network}/*/{project.channel}*.D/*.*.*.*.D.{time.year}.{time.julday:03d}'
        dataset: 'D:\DataSets-Local\1405-04-03\{project.name}-Dataset_{timestamp}'
