#jupyter nbconvert --execute --to html test-run-with-command-line.ipynb
#jupyter nbconvert --to ipynb --execute ./test-run-with-command-line.ipynb --output "1403-08-27.ipynb"
log:
    level: INFO
    format: "%(asctime)s | %(levelname)s | %(message)s"
    mode: both
    colored_console: True
    # Note: The name and path of the log file are set in the settings section for each code.
    filepath: "{path.model}" # Set in the subset config.
    filename_prefix: mk_dataset
    filename: "{project.name}_{timestamp}" # if set to "now", the current date set as the logfile name.
    filename_timestamp: null

dataset:
    data_format:
        # https://seisbench.readthedocs.io/en/stable/pages/data/data_format.html#the-data-format-group
        dimension_order: NCW
        component_order: ZNE
        sampling_rate: 100
        measurement: velocity
        unit: counts
        instrument_response: not restituted
    split_ratios:
        train: 0.05
        dev: 0.1
        test: 0.85
    # Exclude the problematic sample from the DataSet. (Merged Dataset)
    # This sample triggers an unexpected error during dataset processing,
    # and the root cause has not been identified.
    # Since this sample is not significant for the evaluation, it is skipped
    # to ensure stable execution.
    manual_excluded_samples: [23972]

dataloader:
    train:
        batch_size: 256
        shuffle: true
        num_workers: 0
    dev:
        batch_size: 256
        shuffle: false
        num_workers: 0
    test:
        batch_size: 256
        shuffle: false
        num_workers: 0

augmentation:
  - cls: SeisRoutine.seisbench.waveform.Tapering
    
  - cls: seisbench.generate.Normalize
    demean_axis: -1
    amp_norm_axis: -1
    amp_norm_type: peak

  - cls: seisbench.generate.FixedWindow
    p0: -1500          # -15 * sps
    windowlen: 6000    # 60 * sps
    strategy: pad
    key: X

  - cls: seisbench.generate.WindowAroundSample
    metadata_keys: "{phase_dict_keys}"
    samples_before: 2000
    windowlen: 5000
    selection: random
    strategy: variable

  - cls:  seisbench.generate.GaussianNoise
    scale: [0.0, 0.02]
    key: X

  - cls: seisbench.generate.RandomWindow
    windowlen: 3001

  - cls: seisbench.generate.ChangeDtype
    dtype: "{np.float32}"

  - cls: seisbench.generate.ProbabilisticLabeller
    label_columns: "{phase_dict}"
    model_labels: NPS
    sigma: 30
    dim: 0

seed: 42

model:
    cls: seisbench.models.PhaseNet
    weights_type: original # "scratch", "original", or etc. 
    version_str: '{timestamp}'
    hyperparameters:
        norm: peak
        phases: 'NPS'

path:
    dataset: 'C:\Users\ikahbasi\Documents\DataSets-Local\1405-04-03\Merged_Dataset_2026-06-24T15-15-22'
    model: 'D:\Models\{model.cls}_{timestamp}'

train_stages:
  - name: stage1
    optimizer:
        cls: torch.optim.Adam
        lr: 1.0e-4
    epochs: 1
    lr_scheduler:
        cls: torch.optim.lr_scheduler.ReduceLROnPlateau
        mode: min
        factor: 0.2
        patience: 3
        threshold: 1.0e-4
        threshold_mode: rel
        cooldown: 0
        min_lr: 0
        eps: 1.0e-08
    early_stopping:
        cls: SeisRoutine.seisbench.training.EarlyStopping
        patience: 10
        min_improvement_percent: 10